[build]
functions = "./functions"

[[redirects]]
from = "./popular-movies/*"
to = "/.netlify/functions/popularMovies"

[[redirects]]
from = "./search-movies/*"
to = "/.netlify/functions/searchMovies"

[[redirects]]
from = "/"
to = "/.netlify/index.html"

[[redirects]]
from = "/test"
to = "/.netlify/functions/test"